  version: '3.8' 

  services:
    backend:
      container_name: backend
      image: ecom/backend:latest
      build: ./backend
      env_file:
        ./backend/.env
      environment:
        - DB_HOST=db
      ports:
        - "8000:8000"
      volumes:
        - ./backend:/app/backend/
      restart: always
      depends_on:
        - db
    
    db:
      container_name: db
      image: postgres
      env_file:
        ./backend/.env
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      ports:
        - 5423:5432
      expose:
        - "5423"
      restart: always
    
    nginx:
      container_name: nginx
      image: exom-nginx:latest
      build: ./nginx
      ports:
        - "80:80"
      volumes:
        - ./frontend/build:/usr/share/nginx/html
        - ./backend/staticfiles:/usr/share/nginx/backend
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      restart: always
      depends_on:
        - backend
        - frontend
    
    frontend:
      container_name: frontend
      image: ecom/frontend:latest
      build: 
        context: ./frontend
        cache_from: 
        - invalidation
      env_file:
        ./frontend/.env
      ports:
        - "3000:3000"
      volumes:
        - ./frontend/:/app/frontend/
      restart: always
      stdin_open: true
      
  volumes:
      postgres_data:
