# Generated by Django 4.2.11 on 2024-05-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hellow', models.CharField(max_length=100, verbose_name='hellow')),
            ],
        ),
    ]
